"""empty message

Revision ID: 471405260d87
Revises: e3371d36e2a0
Create Date: 2020-05-15 18:15:20.737299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '471405260d87'
down_revision = 'e3371d36e2a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('assoc_role_user',
    sa.Column('role_id', sa.BigInteger(), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('assoc_role_user')
    op.drop_table('roles')
    # ### end Alembic commands ###
