"""empty message

Revision ID: b6834d04f5f5
Revises: 471405260d87
Create Date: 2020-05-17 15:16:51.421682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6834d04f5f5'
down_revision = '471405260d87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('msg_text', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'msg_text')
    # ### end Alembic commands ###
